CREATE TABLE public.company (
	id text NOT NULL,
	created_at timestamptz NULL DEFAULT now(),
	"name" text NULL,
	CONSTRAINT company_pkey PRIMARY KEY (id)
);

-- Drop table

-- DROP TABLE public.employee;

CREATE TABLE public.employee (
	id text NOT NULL,
	created_at timestamptz NULL DEFAULT now(),
	"name" text NULL,
	rating text NULL,
	company_id text NULL,
	CONSTRAINT employee_pkey PRIMARY KEY (id),
	CONSTRAINT employee_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.company(id)
);


-- Drop table

-- DROP TABLE public.employees;

CREATE TABLE public.employees (
	id int8 NOT NULL,
	"name" text NULL,
	"Monthly" text NULL,
	"Days" int8 NULL,
	"Total" text NULL,
	"National pension" text NULL,
	"Health Insurance" text NULL,
	"Long -term care" text NULL,
	"Employment Insurance" text NULL,
	"Income tax" text NULL,
	"Resident Tax" text NULL,
	"National (Company)" text NULL,
	"Total Tax" text NULL,
	"Annual expenditure
(Salary+tax+
severance pay)" text NULL,
	"Monthly expenditure
(Salary+tax)" text NULL,
	"Daily expenditure
(30 day standard)" text NULL,
	"Days Participated" int8 NULL,
	"Payment during constructioin" text NULL,
	CONSTRAINT er_pkey PRIMARY KEY (id)
);

-- Drop table

-- DROP TABLE public."event";

CREATE TABLE public."event" (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamptz NULL DEFAULT now(),
	"start" date NULL,
	"end" date NULL,
	employee_id text NULL,
	title text NULL,
	site_id int8 NULL,
	"event_type" event_type NULL,
	event_sub_type int8 NULL,
	CONSTRAINT event_pkey PRIMARY KEY (id),
	CONSTRAINT event_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employee(id),
	CONSTRAINT event_event_sub_type_fkey FOREIGN KEY (event_sub_type) REFERENCES public.event_sub_type(id),
	CONSTRAINT event_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_site(id)
);
-- Drop table

-- DROP TABLE public.event_sub_type;

CREATE TABLE public.event_sub_type (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamptz NULL DEFAULT now(),
	"event_type" event_type NULL,
	event_sub_type varchar NULL,
	CONSTRAINT event_sub_type_pkey PRIMARY KEY (id)
);
-- Drop table

-- DROP TABLE public.profiles;

CREATE TABLE public.profiles (
	id uuid NOT NULL,
	updated_at timestamptz NULL,
	username text NULL,
	company text NULL,
	job_title text NULL,
	avatar_url text NULL,
	website text NULL,
	CONSTRAINT profiles_pkey PRIMARY KEY (id),
	CONSTRAINT profiles_username_key UNIQUE (username),
	CONSTRAINT username_length CHECK ((char_length(username) >= 3)),
	CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);

-- Drop table

-- DROP TABLE public.project_site;

CREATE TABLE public.project_site (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_at timestamptz NULL DEFAULT now(),
	"location" text NULL,
	color text NULL,
	CONSTRAINT project_site_pkey PRIMARY KEY (id)
);
